### PR TITLE
Retired season 2 w/o dlc as its no longer a proper category

### PR DESCRIPTION
**Pull request by Tinosaurus**
Also:
Added Ambrose to premade S2 link.
Added Ambrose to dropdown list.
added .idea to gitignore because it wasnt there already and git just kept complaining about it.

LGTM if theres any issues ping me somewhere

### CODE REVIEW

**Comment by solderq35** [comment]
Is Ambrose supposed to be in Trilogy category? @Tinosaurus 

image

**Comment by Tinosaurus** [comment]
I could see it being in there, no reason to not have it. Ill do a quick commit to add it.

**Comment by solderq35** [comment]
I think I added it, if it looks good on your end I'll merge the PR @Tinosaurus 

image

**Comment by solderq35** [comment]
image

Wait this doesn't look right, dropdown and s2 aren't matching. Gonna boot up the game for once to check where the level goes ig

**Comment by Tinosaurus** [comment]
Ambrose should be after Whittleton, before Sgail.

**Comment by solderq35** [comment]
Should be good now

image
image

**Comment by Tinosaurus** [comment]
Yeah pulled and checked, LGTM also.

**Pull request merged**
